package synthesize

// Voice represents ISO-639 language codes
// Taken from https://cloud.google.com/translate/docs/languages
// es-MX, es-ES or en-US, en-UK, en-AU voices are converted to regions and no longer available on web version, they are using different domains rather than language codes.
type Voice string

const (
	AfrikaansVoice           Voice = "af"
	AlbanianVoice            Voice = "sq"
	AmharicVoice             Voice = "am"
	ArabicVoice              Voice = "ar"
	BengaliVoice             Voice = "bn"
	BosnianVoice             Voice = "bs"
	BulgarianVoice           Voice = "bg"
	CantoneseVoice           Voice = "yue"
	CatalanVoice             Voice = "ca"
	ChineseSimplifiedVoice   Voice = "zh"
	ChineseTraditionalVoice  Voice = "zh-TW"
	CroatianVoice            Voice = "hr"
	CzechVoice               Voice = "cs"
	DanishVoice              Voice = "da"
	DutchVoice               Voice = "nl"
	EnglishVoice             Voice = "en"
	EstonianVoice            Voice = "et"
	FilipinoVoice            Voice = "tl"
	FinnishVoice             Voice = "fi"
	FrenchVoice              Voice = "fr"
	FrenchCanadianVoice      Voice = "fr-CA"
	GalicianVoice            Voice = "gl"
	GermanVoice              Voice = "de"
	GreekVoice               Voice = "el"
	GujaratiVoice            Voice = "gu"
	HausaVoice               Voice = "ha"
	HebrewVoice              Voice = "iw"
	HindiVoice               Voice = "hi"
	HungarianVoice           Voice = "hu"
	IcelandicVoice           Voice = "is"
	IndonesianVoice          Voice = "id"
	ItalianVoice             Voice = "it"
	JapaneseVoice            Voice = "ja"
	JavaneseVoice            Voice = "jw"
	KhmerVoice               Voice = "km"
	KoreanVoice              Voice = "ko"
	LatinVoice               Voice = "la"
	LatvianVoice             Voice = "lv"
	LithuanianVoice          Voice = "lt"
	MalayVoice               Voice = "ms"
	MalayalamVoice           Voice = "ml"
	MarathiVoice             Voice = "mr"
	MyanmarVoice             Voice = "my"
	NepaliVoice              Voice = "ne"
	NorwegianVoice           Voice = "no"
	PolishVoice              Voice = "pl"
	PortugueseBrazilianVoice Voice = "pt"
	PortugueseVoice          Voice = "pt-PT"
	PunjabiVoice             Voice = "pa"
	RomanianVoice            Voice = "ro"
	RussianVoice             Voice = "ru"
	SerbianVoice             Voice = "sr"
	SinhalaVoice             Voice = "si"
	SlovakVoice              Voice = "sk"
	SpanishVoice             Voice = "es"
	SundaneseVoice           Voice = "su"
	SwahiliVoice             Voice = "sw"
	SwedishVoice             Voice = "sv"
	TamilVoice               Voice = "ta"
	TeluguVoice              Voice = "te"
	ThaiVoice                Voice = "th"
	UkrainianVoice           Voice = "uk"
	UrduVoice                Voice = "ur"
	VietnameseVoice          Voice = "vi"
	WelshVoice               Voice = "cy"
)
